### ISSUE TITLE
[Bug]: Performance Issue due to Filesystem call

### ISSUE THREAD

**Issue by austincarpenter** [LukasFreyCZ/filament-icon-picker#62]
### What happened?

On every Filament request, this package attempts to create an "icon-picker-icons" directory for use of custom uploaded files.

https://github.com/lukas-frey/filament-icon-picker/blob/7c28d7ff9e4fd3bf1f28443965f77d61ff280b7e/src/IconPickerServiceProvider.php

I don't use the custom icons, nor have the solution as to where to move this code, but I do know it's a bottleneck, especially if accessing the cloud storage has any latency.

### How to reproduce the bug

Load any Filament page.

### Package Version

3

### PHP Version

8.4

### Laravel Version

12

**Comment by Ant-V** [comment]
I can confirm this bug. At times it even generates 429 errors.
Unable to write file at location: icon-picker-icons/. Error executing "PutObject" on "https://fls-xxxx.cloudflarestorage.com/icon-picker-icons/"; AWS HTTP error: Client error: `PUT https://fls-xxxx.cloudflarestorage.com/icon-picker-icons/` resulted in a `429 Too Many Requests` response:
icon-picker-icons/` resulted in a `429 Too Many Requests` response:
<?xml version="1.0" encoding="UTF-8"?><Error><Code>ServiceUnavailable</Code><Message>Reduce your concurrent request rate (truncated...)
 ServiceUnavailable (client): Reduce your concurrent request rate for the same object. - <?xml version="1.0" encoding="UTF-8"?><Error><Code>ServiceUnavailable</Code><Message>Reduce your concurrent request rate for the same object.</Message></Error>

**Comment by lukas-frey** [comment]
Hi, please update to 5.x, this issue is now fixed and on top of it we have improved the performance of the icon picker by 5.2x of the original 4.x version.

If you find any other problems, feel free to open a new issue

**Comment by arshaplus** [comment]
> Hi, please update to 5.x, this issue is now fixed and on top of it we have improved the performance of the icon picker by 5.2x of the original 4.x version.
> 
> If you find any other problems, feel free to open a new issue

### Still happening

Thanks for addressing this issue, but unfortunately the filesystem call is still happening on every request.

In the current `IconPickerServiceProvider`, `Storage::disk('public')->makeDirectory(IconSet::CUSTOM_DIRECTORY)` is still called inside `callAfterResolving()`.

This means that whenever `IconFactory` is resolved, the package still makes a filesystem call to create/check the `icon-picker-icons` directory, even if custom icons are not being used.

This is especially problematic when the `public` disk is backed by S3/MinIO or another remote filesystem, where this call can add noticeable latency to every request.

At the very least, could the package make the disk configurable instead of hard-coding `public`?

For example, having something like:

```php
'filesystem_disk' => env('FILAMENT_ICON_PICKER_DISK', 'public'),
```

and using that disk for both `makeDirectory()` and the custom icon set would allow applications to configure the storage appropriately.

Ideally, the directory creation should also only happen when custom icon uploads are actually being used, rather than during every request.

Could you please take another look at this issue? Thanks!
